"""Shared constants for the server-rendered operator console."""

_CONTEXT_QUERY_KEYS = ("config_dir", "database_url")
_DEFAULT_DASHBOARD_RUN_LIMIT = 6
_DEFAULT_DASHBOARD_FAILURE_LIMIT = 6
_DEFAULT_ARTICLE_LIMIT = 25
_DEFAULT_PUBLISH_JOB_LIMIT = 25
_SCHEDULER_LIVE_VALUES = {"1", "on", "true", "yes"}
_MANUAL_UPLOAD_CHANNELS = frozenset({"ghost", "linkedin", "threads"})
_KOREAN_LABELS = {
    "analysis": "분석",
    "approve": "승인",
    "approved": "승인됨",
    "article_extract": "본문 추출",
    "backfill": "백필",
    "brief_build": "브리프 생성",
    "cancelled": "취소됨",
    "canonical_url": "대표 URL 중복",
    "discover": "수집",
    "discovery_only": "탐색 전용",
    "diplomacy": "외교",
    "disaster": "재난",
    "draft_generate": "초안 생성",
    "dry_run": "드라이런",
    "edit": "수정",
    "enrich": "기사 보강",
    "enriched": "보강 완료",
    "existing": "기존 있음",
    "failed": "실패",
    "finance": "금융",
    "ghost": "Ghost",
    "health": "보건",
    "html_fetch": "HTML 수집",
    "ingest": "수집 저장",
    "in_progress": "진행 중",
    "legal": "법률",
    "linkedin": "LinkedIn",
    "manual_local": "로컬 수동 실행",
    "news": "뉴스",
    "normalized_title_hash": "정규화 제목 중복",
    "opinion": "의견",
    "other": "기타",
    "partial": "부분 완료",
    "pending": "대기",
    "pending_review": "검토 대기",
    "politics": "정치",
    "practical_how_to": "실무 가이드",
    "product": "제품",
    "product_update": "제품 업데이트",
    "publish_due": "발행 예정 처리",
    "published": "발행 완료",
    "publishing": "발행 중",
    "recent_fingerprint": "최근 내용 중복",
    "reject": "반려",
    "rejected": "반려됨",
    "restricted": "제한됨",
    "run_local": "뉴스 수집",
    "reusable": "재사용 가능",
    "rss_discovered": "RSS 수집",
    "running": "실행 중",
    "saved": "저장",
    "schedule": "예약",
    "scheduled": "예약됨",
    "security": "안보",
    "skipped": "건너뜀",
    "source_identity": "소스 고유 ID 중복",
    "succeeded": "성공",
    "summary_regenerate": "요약 재생성",
    "threads": "Threads",
    "topic_takeaway": "핵심 요약",
    "trend_insight": "트렌드 인사이트",
    "tutorial": "튜토리얼",
    "x": "X",
}
